//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package montranMessage.iso.std.iso._20022.tech.xsd.camt_029_001;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the montranMessage.iso.std.iso._20022.tech.xsd.camt_029_001 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.029.001.03", "Document");
    private final static QName _Document08_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.029.001.08", "Document08");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: montranMessage.iso.std.iso._20022.tech.xsd.camt_029_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResolutionOfInvestigationV03 }
     * 
     * @return
     *     the new instance of {@link ResolutionOfInvestigationV03 }
     */
    public ResolutionOfInvestigationV03 createResolutionOfInvestigationV03() {
        return new ResolutionOfInvestigationV03();
    }

    /**
     * Create an instance of {@link ResolutionOfInvestigationV08 }
     * 
     * @return
     *     the new instance of {@link ResolutionOfInvestigationV08 }
     */
    public ResolutionOfInvestigationV08 createResolutionOfInvestigationV08() {
        return new ResolutionOfInvestigationV08();
    }

    /**
     * Create an instance of {@link Document }
     * 
     * @return
     *     the new instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     * @return
     *     the new instance of {@link AccountIdentification4Choice }
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link AccountIdentificationIBAN }
     * 
     * @return
     *     the new instance of {@link AccountIdentificationIBAN }
     */
    public AccountIdentificationIBAN createAccountIdentificationIBAN() {
        return new AccountIdentificationIBAN();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link AccountSchemeName1Choice }
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     * @return
     *     the new instance of {@link ActiveCurrencyAndAmount }
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmendmentInformationDetails6 }
     * 
     * @return
     *     the new instance of {@link AmendmentInformationDetails6 }
     */
    public AmendmentInformationDetails6 createAmendmentInformationDetails6() {
        return new AmendmentInformationDetails6();
    }

    /**
     * Create an instance of {@link CashAccount16 }
     * 
     * @return
     *     the new instance of {@link CashAccount16 }
     */
    public CashAccount16 createCashAccount16() {
        return new CashAccount16();
    }

    /**
     * Create an instance of {@link CashAccount17 }
     * 
     * @return
     *     the new instance of {@link CashAccount17 }
     */
    public CashAccount17 createCashAccount17() {
        return new CashAccount17();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     * @return
     *     the new instance of {@link CategoryPurpose1Choice }
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link ChargesInformation5 }
     * 
     * @return
     *     the new instance of {@link ChargesInformation5 }
     */
    public ChargesInformation5 createChargesInformation5() {
        return new ChargesInformation5();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice }
     * 
     * @return
     *     the new instance of {@link ClearingSystemIdentification3Choice }
     */
    public ClearingSystemIdentification3Choice createClearingSystemIdentification3Choice() {
        return new ClearingSystemIdentification3Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceInformation2 }
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType1Choice }
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType2 }
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     * @return
     *     the new instance of {@link DateAndPlaceOfBirth }
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link FinancialInstitution4 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitution4 }
     */
    public FinancialInstitution4 createFinancialInstitution4() {
        return new FinancialInstitution4();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitutionIdentification7 }
     */
    public FinancialInstitutionIdentification7 createFinancialInstitutionIdentification7() {
        return new FinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link FinancialInstitution5 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitution5 }
     */
    public FinancialInstitution5 createFinancialInstitution5() {
        return new FinancialInstitution5();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitutionIdentification8 }
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericAccountIdentification1 }
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericOrganisationIdentification1 }
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericPersonIdentification1 }
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     * @return
     *     the new instance of {@link LocalInstrument2Choice }
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link MandateRelatedInformation6 }
     * 
     * @return
     *     the new instance of {@link MandateRelatedInformation6 }
     */
    public MandateRelatedInformation6 createMandateRelatedInformation6() {
        return new MandateRelatedInformation6();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentification4 }
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link OrganisationIdentification5 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentification5 }
     */
    public OrganisationIdentification5 createOrganisationIdentification5() {
        return new OrganisationIdentification5();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentificationSchemeName1Choice }
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification32 }
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link PartyIdentification33 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification33 }
     */
    public PartyIdentification33 createPartyIdentification33() {
        return new PartyIdentification33();
    }

    /**
     * Create an instance of {@link PartyIdentification34 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification34 }
     */
    public PartyIdentification34 createPartyIdentification34() {
        return new PartyIdentification34();
    }

    /**
     * Create an instance of {@link PartyIdentification35 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification35 }
     */
    public PartyIdentification35 createPartyIdentification35() {
        return new PartyIdentification35();
    }

    /**
     * Create an instance of {@link PartyIdentification36 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification36 }
     */
    public PartyIdentification36 createPartyIdentification36() {
        return new PartyIdentification36();
    }

    /**
     * Create an instance of {@link PartyIdentification37 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification37 }
     */
    public PartyIdentification37 createPartyIdentification37() {
        return new PartyIdentification37();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     * @return
     *     the new instance of {@link Party6Choice }
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link Party8Choice }
     * 
     * @return
     *     the new instance of {@link Party8Choice }
     */
    public Party8Choice createParty8Choice() {
        return new Party8Choice();
    }

    /**
     * Create an instance of {@link PartyPrivate1 }
     * 
     * @return
     *     the new instance of {@link PartyPrivate1 }
     */
    public PartyPrivate1 createPartyPrivate1() {
        return new PartyPrivate1();
    }

    /**
     * Create an instance of {@link PaymentIdentification3 }
     * 
     * @return
     *     the new instance of {@link PaymentIdentification3 }
     */
    public PaymentIdentification3 createPaymentIdentification3() {
        return new PaymentIdentification3();
    }

    /**
     * Create an instance of {@link PersonIdentification4 }
     * 
     * @return
     *     the new instance of {@link PersonIdentification4 }
     */
    public PersonIdentification4 createPersonIdentification4() {
        return new PersonIdentification4();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     * @return
     *     the new instance of {@link PersonIdentification5 }
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link PersonIdentificationSchemeName1Choice }
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress7 }
     * 
     * @return
     *     the new instance of {@link PostalAddress7 }
     */
    public PostalAddress7 createPostalAddress7() {
        return new PostalAddress7();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     * @return
     *     the new instance of {@link Purpose2Choice }
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     * @return
     *     the new instance of {@link RemittanceInformation5 }
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link RestrictedIdentification1 }
     * 
     * @return
     *     the new instance of {@link RestrictedIdentification1 }
     */
    public RestrictedIdentification1 createRestrictedIdentification1() {
        return new RestrictedIdentification1();
    }

    /**
     * Create an instance of {@link RestrictedIdentification2 }
     * 
     * @return
     *     the new instance of {@link RestrictedIdentification2 }
     */
    public RestrictedIdentification2 createRestrictedIdentification2() {
        return new RestrictedIdentification2();
    }

    /**
     * Create an instance of {@link RestrictedPersonIdentificationSchemaName2Choice }
     * 
     * @return
     *     the new instance of {@link RestrictedPersonIdentificationSchemaName2Choice }
     */
    public RestrictedPersonIdentificationSchemaName2Choice createRestrictedPersonIdentificationSchemaName2Choice() {
        return new RestrictedPersonIdentificationSchemaName2Choice();
    }

    /**
     * Create an instance of {@link RestrictedInstitutionSchemaName1Choice }
     * 
     * @return
     *     the new instance of {@link RestrictedInstitutionSchemaName1Choice }
     */
    public RestrictedInstitutionSchemaName1Choice createRestrictedInstitutionSchemaName1Choice() {
        return new RestrictedInstitutionSchemaName1Choice();
    }

    /**
     * Create an instance of {@link ServiceLevel9Choice }
     * 
     * @return
     *     the new instance of {@link ServiceLevel9Choice }
     */
    public ServiceLevel9Choice createServiceLevel9Choice() {
        return new ServiceLevel9Choice();
    }

    /**
     * Create an instance of {@link SettlementInformation13 }
     * 
     * @return
     *     the new instance of {@link SettlementInformation13 }
     */
    public SettlementInformation13 createSettlementInformation13() {
        return new SettlementInformation13();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     * @return
     *     the new instance of {@link StructuredRemittanceInformation7 }
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentInformation3 }
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentType2 }
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentType1Choice }
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link RemittanceAmount1 }
     * 
     * @return
     *     the new instance of {@link RemittanceAmount1 }
     */
    public RemittanceAmount1 createRemittanceAmount1() {
        return new RemittanceAmount1();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     * @return
     *     the new instance of {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     * @return
     *     the new instance of {@link DocumentAdjustment1 }
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link CaseAssignment2 }
     * 
     * @return
     *     the new instance of {@link CaseAssignment2 }
     */
    public CaseAssignment2 createCaseAssignment2() {
        return new CaseAssignment2();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation3 }
     * 
     * @return
     *     the new instance of {@link OriginalGroupInformation3 }
     */
    public OriginalGroupInformation3 createOriginalGroupInformation3() {
        return new OriginalGroupInformation3();
    }

    /**
     * Create an instance of {@link Party7Choice }
     * 
     * @return
     *     the new instance of {@link Party7Choice }
     */
    public Party7Choice createParty7Choice() {
        return new Party7Choice();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation22 }
     * 
     * @return
     *     the new instance of {@link PaymentTypeInformation22 }
     */
    public PaymentTypeInformation22 createPaymentTypeInformation22() {
        return new PaymentTypeInformation22();
    }

    /**
     * Create an instance of {@link CancellationStatusReason1Choice }
     * 
     * @return
     *     the new instance of {@link CancellationStatusReason1Choice }
     */
    public CancellationStatusReason1Choice createCancellationStatusReason1Choice() {
        return new CancellationStatusReason1Choice();
    }

    /**
     * Create an instance of {@link CancellationStatusReasonInformation1 }
     * 
     * @return
     *     the new instance of {@link CancellationStatusReasonInformation1 }
     */
    public CancellationStatusReasonInformation1 createCancellationStatusReasonInformation1() {
        return new CancellationStatusReasonInformation1();
    }

    /**
     * Create an instance of {@link InvestigationStatus2Choice }
     * 
     * @return
     *     the new instance of {@link InvestigationStatus2Choice }
     */
    public InvestigationStatus2Choice createInvestigationStatus2Choice() {
        return new InvestigationStatus2Choice();
    }

    /**
     * Create an instance of {@link PaymentTransactionInformation33 }
     * 
     * @return
     *     the new instance of {@link PaymentTransactionInformation33 }
     */
    public PaymentTransactionInformation33 createPaymentTransactionInformation33() {
        return new PaymentTransactionInformation33();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference131 }
     * 
     * @return
     *     the new instance of {@link OriginalTransactionReference131 }
     */
    public OriginalTransactionReference131 createOriginalTransactionReference131() {
        return new OriginalTransactionReference131();
    }

    /**
     * Create an instance of {@link UnderlyingTransaction3 }
     * 
     * @return
     *     the new instance of {@link UnderlyingTransaction3 }
     */
    public UnderlyingTransaction3 createUnderlyingTransaction3() {
        return new UnderlyingTransaction3();
    }

    /**
     * Create an instance of {@link Document2 }
     * 
     * @return
     *     the new instance of {@link Document2 }
     */
    public Document2 createDocument2() {
        return new Document2();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice2 }
     * 
     * @return
     *     the new instance of {@link AccountIdentification4Choice2 }
     */
    public AccountIdentification4Choice2 createAccountIdentification4Choice2() {
        return new AccountIdentification4Choice2();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice2 }
     * 
     * @return
     *     the new instance of {@link AccountSchemeName1Choice2 }
     */
    public AccountSchemeName1Choice2 createAccountSchemeName1Choice2() {
        return new AccountSchemeName1Choice2();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount2 }
     * 
     * @return
     *     the new instance of {@link ActiveOrHistoricCurrencyAndAmount2 }
     */
    public ActiveOrHistoricCurrencyAndAmount2 createActiveOrHistoricCurrencyAndAmount2() {
        return new ActiveOrHistoricCurrencyAndAmount2();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification5 }
     * 
     * @return
     *     the new instance of {@link BranchAndFinancialInstitutionIdentification5 }
     */
    public BranchAndFinancialInstitutionIdentification5 createBranchAndFinancialInstitutionIdentification5() {
        return new BranchAndFinancialInstitutionIdentification5();
    }

    /**
     * Create an instance of {@link Case4 }
     * 
     * @return
     *     the new instance of {@link Case4 }
     */
    public Case4 createCase4() {
        return new Case4();
    }

    /**
     * Create an instance of {@link CaseAssignment4 }
     * 
     * @return
     *     the new instance of {@link CaseAssignment4 }
     */
    public CaseAssignment4 createCaseAssignment4() {
        return new CaseAssignment4();
    }

    /**
     * Create an instance of {@link CashAccount24 }
     * 
     * @return
     *     the new instance of {@link CashAccount24 }
     */
    public CashAccount24 createCashAccount24() {
        return new CashAccount24();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice2 }
     * 
     * @return
     *     the new instance of {@link CategoryPurpose1Choice2 }
     */
    public CategoryPurpose1Choice2 createCategoryPurpose1Choice2() {
        return new CategoryPurpose1Choice2();
    }

    /**
     * Create an instance of {@link Charges2 }
     * 
     * @return
     *     the new instance of {@link Charges2 }
     */
    public Charges2 createCharges2() {
        return new Charges2();
    }

    /**
     * Create an instance of {@link ClaimNonReceipt1Choice }
     * 
     * @return
     *     the new instance of {@link ClaimNonReceipt1Choice }
     */
    public ClaimNonReceipt1Choice createClaimNonReceipt1Choice() {
        return new ClaimNonReceipt1Choice();
    }

    /**
     * Create an instance of {@link ClaimNonReceiptRejectReason1Choice }
     * 
     * @return
     *     the new instance of {@link ClaimNonReceiptRejectReason1Choice }
     */
    public ClaimNonReceiptRejectReason1Choice createClaimNonReceiptRejectReason1Choice() {
        return new ClaimNonReceiptRejectReason1Choice();
    }

    /**
     * Create an instance of {@link ClaimNonReceipt1 }
     * 
     * @return
     *     the new instance of {@link ClaimNonReceipt1 }
     */
    public ClaimNonReceipt1 createClaimNonReceipt1() {
        return new ClaimNonReceipt1();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice2 }
     * 
     * @return
     *     the new instance of {@link ClearingSystemIdentification3Choice2 }
     */
    public ClearingSystemIdentification3Choice2 createClearingSystemIdentification3Choice2() {
        return new ClearingSystemIdentification3Choice2();
    }

    /**
     * Create an instance of {@link Compensation1 }
     * 
     * @return
     *     the new instance of {@link Compensation1 }
     */
    public Compensation1 createCompensation1() {
        return new Compensation1();
    }

    /**
     * Create an instance of {@link CompensationReason1Choice }
     * 
     * @return
     *     the new instance of {@link CompensationReason1Choice }
     */
    public CompensationReason1Choice createCompensationReason1Choice() {
        return new CompensationReason1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation22 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceInformation22 }
     */
    public CreditorReferenceInformation22 createCreditorReferenceInformation22() {
        return new CreditorReferenceInformation22();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice2 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType1Choice2 }
     */
    public CreditorReferenceType1Choice2 createCreditorReferenceType1Choice2() {
        return new CreditorReferenceType1Choice2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType22 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType22 }
     */
    public CreditorReferenceType22 createCreditorReferenceType22() {
        return new CreditorReferenceType22();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     * @return
     *     the new instance of {@link DateAndPlaceOfBirth1 }
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification82 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitutionIdentification82 }
     */
    public FinancialInstitutionIdentification82 createFinancialInstitutionIdentification82() {
        return new FinancialInstitutionIdentification82();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification12 }
     * 
     * @return
     *     the new instance of {@link GenericAccountIdentification12 }
     */
    public GenericAccountIdentification12 createGenericAccountIdentification12() {
        return new GenericAccountIdentification12();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericFinancialIdentification1 }
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification12 }
     * 
     * @return
     *     the new instance of {@link GenericOrganisationIdentification12 }
     */
    public GenericOrganisationIdentification12 createGenericOrganisationIdentification12() {
        return new GenericOrganisationIdentification12();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification12 }
     * 
     * @return
     *     the new instance of {@link GenericPersonIdentification12 }
     */
    public GenericPersonIdentification12 createGenericPersonIdentification12() {
        return new GenericPersonIdentification12();
    }

    /**
     * Create an instance of {@link InvestigationStatus4Choice }
     * 
     * @return
     *     the new instance of {@link InvestigationStatus4Choice }
     */
    public InvestigationStatus4Choice createInvestigationStatus4Choice() {
        return new InvestigationStatus4Choice();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice2 }
     * 
     * @return
     *     the new instance of {@link LocalInstrument2Choice2 }
     */
    public LocalInstrument2Choice2 createLocalInstrument2Choice2() {
        return new LocalInstrument2Choice2();
    }

    /**
     * Create an instance of {@link OrganisationIdentification8 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentification8 }
     */
    public OrganisationIdentification8 createOrganisationIdentification8() {
        return new OrganisationIdentification8();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice2 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentificationSchemeName1Choice2 }
     */
    public OrganisationIdentificationSchemeName1Choice2 createOrganisationIdentificationSchemeName1Choice2() {
        return new OrganisationIdentificationSchemeName1Choice2();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation29 }
     * 
     * @return
     *     the new instance of {@link OriginalGroupInformation29 }
     */
    public OriginalGroupInformation29 createOriginalGroupInformation29() {
        return new OriginalGroupInformation29();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference27 }
     * 
     * @return
     *     the new instance of {@link OriginalTransactionReference27 }
     */
    public OriginalTransactionReference27 createOriginalTransactionReference27() {
        return new OriginalTransactionReference27();
    }

    /**
     * Create an instance of {@link Party34Choice }
     * 
     * @return
     *     the new instance of {@link Party34Choice }
     */
    public Party34Choice createParty34Choice() {
        return new Party34Choice();
    }

    /**
     * Create an instance of {@link Party35Choice }
     * 
     * @return
     *     the new instance of {@link Party35Choice }
     */
    public Party35Choice createParty35Choice() {
        return new Party35Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification125 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification125 }
     */
    public PartyIdentification125 createPartyIdentification125() {
        return new PartyIdentification125();
    }

    /**
     * Create an instance of {@link PaymentTransaction90 }
     * 
     * @return
     *     the new instance of {@link PaymentTransaction90 }
     */
    public PaymentTransaction90 createPaymentTransaction90() {
        return new PaymentTransaction90();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation25 }
     * 
     * @return
     *     the new instance of {@link PaymentTypeInformation25 }
     */
    public PaymentTypeInformation25 createPaymentTypeInformation25() {
        return new PaymentTypeInformation25();
    }

    /**
     * Create an instance of {@link PersonIdentification13 }
     * 
     * @return
     *     the new instance of {@link PersonIdentification13 }
     */
    public PersonIdentification13 createPersonIdentification13() {
        return new PersonIdentification13();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice2 }
     * 
     * @return
     *     the new instance of {@link PersonIdentificationSchemeName1Choice2 }
     */
    public PersonIdentificationSchemeName1Choice2 createPersonIdentificationSchemeName1Choice2() {
        return new PersonIdentificationSchemeName1Choice2();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     * @return
     *     the new instance of {@link PostalAddress6 }
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link Purpose2Choice2 }
     * 
     * @return
     *     the new instance of {@link Purpose2Choice2 }
     */
    public Purpose2Choice2 createPurpose2Choice2() {
        return new Purpose2Choice2();
    }

    /**
     * Create an instance of {@link RemittanceInformation15 }
     * 
     * @return
     *     the new instance of {@link RemittanceInformation15 }
     */
    public RemittanceInformation15 createRemittanceInformation15() {
        return new RemittanceInformation15();
    }

    /**
     * Create an instance of {@link ResolutionInformation2 }
     * 
     * @return
     *     the new instance of {@link ResolutionInformation2 }
     */
    public ResolutionInformation2 createResolutionInformation2() {
        return new ResolutionInformation2();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     * @return
     *     the new instance of {@link ServiceLevel8Choice }
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link SettlementInstruction4 }
     * 
     * @return
     *     the new instance of {@link SettlementInstruction4 }
     */
    public SettlementInstruction4 createSettlementInstruction4() {
        return new SettlementInstruction4();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation15 }
     * 
     * @return
     *     the new instance of {@link StructuredRemittanceInformation15 }
     */
    public StructuredRemittanceInformation15 createStructuredRemittanceInformation15() {
        return new StructuredRemittanceInformation15();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.029.001.03", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<>(_Document_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document2 }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.029.001.08", name = "Document08")
    public JAXBElement<Document2> createDocument08(Document2 value) {
        return new JAXBElement<>(_Document08_QNAME, Document2 .class, null, value);
    }

}
