//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package montranMessage.iso.std.iso._20022.tech.xsd.pacs_002_001;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the montranMessage.iso.std.iso._20022.tech.xsd.pacs_002_001 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: montranMessage.iso.std.iso._20022.tech.xsd.pacs_002_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV03 }
     * 
     * @return
     *     the new instance of {@link FIToFIPaymentStatusReportV03 }
     */
    public FIToFIPaymentStatusReportV03 createFIToFIPaymentStatusReportV03() {
        return new FIToFIPaymentStatusReportV03();
    }

    /**
     * Create an instance of {@link Document }
     * 
     * @return
     *     the new instance of {@link Document }
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     * @return
     *     the new instance of {@link AccountIdentification4Choice }
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link AccountIdentificationIBAN }
     * 
     * @return
     *     the new instance of {@link AccountIdentificationIBAN }
     */
    public AccountIdentificationIBAN createAccountIdentificationIBAN() {
        return new AccountIdentificationIBAN();
    }

    /**
     * Create an instance of {@link AccountSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link AccountSchemeName1Choice }
     */
    public AccountSchemeName1Choice createAccountSchemeName1Choice() {
        return new AccountSchemeName1Choice();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     * @return
     *     the new instance of {@link ActiveCurrencyAndAmount }
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmendmentInformationDetails6 }
     * 
     * @return
     *     the new instance of {@link AmendmentInformationDetails6 }
     */
    public AmendmentInformationDetails6 createAmendmentInformationDetails6() {
        return new AmendmentInformationDetails6();
    }

    /**
     * Create an instance of {@link CashAccount16 }
     * 
     * @return
     *     the new instance of {@link CashAccount16 }
     */
    public CashAccount16 createCashAccount16() {
        return new CashAccount16();
    }

    /**
     * Create an instance of {@link CashAccount17 }
     * 
     * @return
     *     the new instance of {@link CashAccount17 }
     */
    public CashAccount17 createCashAccount17() {
        return new CashAccount17();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     * @return
     *     the new instance of {@link CategoryPurpose1Choice }
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link ChargesInformation5 }
     * 
     * @return
     *     the new instance of {@link ChargesInformation5 }
     */
    public ChargesInformation5 createChargesInformation5() {
        return new ChargesInformation5();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification3Choice }
     * 
     * @return
     *     the new instance of {@link ClearingSystemIdentification3Choice }
     */
    public ClearingSystemIdentification3Choice createClearingSystemIdentification3Choice() {
        return new ClearingSystemIdentification3Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceInformation2 }
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType1Choice }
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     * @return
     *     the new instance of {@link CreditorReferenceType2 }
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     * @return
     *     the new instance of {@link DateAndPlaceOfBirth }
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link FinancialInstitution4 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitution4 }
     */
    public FinancialInstitution4 createFinancialInstitution4() {
        return new FinancialInstitution4();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitutionIdentification7 }
     */
    public FinancialInstitutionIdentification7 createFinancialInstitutionIdentification7() {
        return new FinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link FinancialInstitution5 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitution5 }
     */
    public FinancialInstitution5 createFinancialInstitution5() {
        return new FinancialInstitution5();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification8 }
     * 
     * @return
     *     the new instance of {@link FinancialInstitutionIdentification8 }
     */
    public FinancialInstitutionIdentification8 createFinancialInstitutionIdentification8() {
        return new FinancialInstitutionIdentification8();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericAccountIdentification1 }
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericOrganisationIdentification1 }
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     * @return
     *     the new instance of {@link GenericPersonIdentification1 }
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     * @return
     *     the new instance of {@link LocalInstrument2Choice }
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link MandateRelatedInformation6 }
     * 
     * @return
     *     the new instance of {@link MandateRelatedInformation6 }
     */
    public MandateRelatedInformation6 createMandateRelatedInformation6() {
        return new MandateRelatedInformation6();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentification4 }
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link OrganisationIdentification5 }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentification5 }
     */
    public OrganisationIdentification5 createOrganisationIdentification5() {
        return new OrganisationIdentification5();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link OrganisationIdentificationSchemeName1Choice }
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification32 }
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link PartyIdentification33 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification33 }
     */
    public PartyIdentification33 createPartyIdentification33() {
        return new PartyIdentification33();
    }

    /**
     * Create an instance of {@link PartyIdentification34 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification34 }
     */
    public PartyIdentification34 createPartyIdentification34() {
        return new PartyIdentification34();
    }

    /**
     * Create an instance of {@link PartyIdentification35 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification35 }
     */
    public PartyIdentification35 createPartyIdentification35() {
        return new PartyIdentification35();
    }

    /**
     * Create an instance of {@link PartyIdentification36 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification36 }
     */
    public PartyIdentification36 createPartyIdentification36() {
        return new PartyIdentification36();
    }

    /**
     * Create an instance of {@link PartyIdentification37 }
     * 
     * @return
     *     the new instance of {@link PartyIdentification37 }
     */
    public PartyIdentification37 createPartyIdentification37() {
        return new PartyIdentification37();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     * @return
     *     the new instance of {@link Party6Choice }
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link Party8Choice }
     * 
     * @return
     *     the new instance of {@link Party8Choice }
     */
    public Party8Choice createParty8Choice() {
        return new Party8Choice();
    }

    /**
     * Create an instance of {@link PartyPrivate1 }
     * 
     * @return
     *     the new instance of {@link PartyPrivate1 }
     */
    public PartyPrivate1 createPartyPrivate1() {
        return new PartyPrivate1();
    }

    /**
     * Create an instance of {@link PaymentIdentification3 }
     * 
     * @return
     *     the new instance of {@link PaymentIdentification3 }
     */
    public PaymentIdentification3 createPaymentIdentification3() {
        return new PaymentIdentification3();
    }

    /**
     * Create an instance of {@link PersonIdentification4 }
     * 
     * @return
     *     the new instance of {@link PersonIdentification4 }
     */
    public PersonIdentification4 createPersonIdentification4() {
        return new PersonIdentification4();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     * @return
     *     the new instance of {@link PersonIdentification5 }
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     * @return
     *     the new instance of {@link PersonIdentificationSchemeName1Choice }
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress7 }
     * 
     * @return
     *     the new instance of {@link PostalAddress7 }
     */
    public PostalAddress7 createPostalAddress7() {
        return new PostalAddress7();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     * @return
     *     the new instance of {@link Purpose2Choice }
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     * @return
     *     the new instance of {@link RemittanceInformation5 }
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link RestrictedIdentification1 }
     * 
     * @return
     *     the new instance of {@link RestrictedIdentification1 }
     */
    public RestrictedIdentification1 createRestrictedIdentification1() {
        return new RestrictedIdentification1();
    }

    /**
     * Create an instance of {@link RestrictedIdentification2 }
     * 
     * @return
     *     the new instance of {@link RestrictedIdentification2 }
     */
    public RestrictedIdentification2 createRestrictedIdentification2() {
        return new RestrictedIdentification2();
    }

    /**
     * Create an instance of {@link RestrictedPersonIdentificationSchemaName2Choice }
     * 
     * @return
     *     the new instance of {@link RestrictedPersonIdentificationSchemaName2Choice }
     */
    public RestrictedPersonIdentificationSchemaName2Choice createRestrictedPersonIdentificationSchemaName2Choice() {
        return new RestrictedPersonIdentificationSchemaName2Choice();
    }

    /**
     * Create an instance of {@link RestrictedInstitutionSchemaName1Choice }
     * 
     * @return
     *     the new instance of {@link RestrictedInstitutionSchemaName1Choice }
     */
    public RestrictedInstitutionSchemaName1Choice createRestrictedInstitutionSchemaName1Choice() {
        return new RestrictedInstitutionSchemaName1Choice();
    }

    /**
     * Create an instance of {@link ServiceLevel9Choice }
     * 
     * @return
     *     the new instance of {@link ServiceLevel9Choice }
     */
    public ServiceLevel9Choice createServiceLevel9Choice() {
        return new ServiceLevel9Choice();
    }

    /**
     * Create an instance of {@link SettlementInformation13 }
     * 
     * @return
     *     the new instance of {@link SettlementInformation13 }
     */
    public SettlementInformation13 createSettlementInformation13() {
        return new SettlementInformation13();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     * @return
     *     the new instance of {@link StructuredRemittanceInformation7 }
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation3 }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentInformation3 }
     */
    public ReferredDocumentInformation3 createReferredDocumentInformation3() {
        return new ReferredDocumentInformation3();
    }

    /**
     * Create an instance of {@link ReferredDocumentType2 }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentType2 }
     */
    public ReferredDocumentType2 createReferredDocumentType2() {
        return new ReferredDocumentType2();
    }

    /**
     * Create an instance of {@link ReferredDocumentType1Choice }
     * 
     * @return
     *     the new instance of {@link ReferredDocumentType1Choice }
     */
    public ReferredDocumentType1Choice createReferredDocumentType1Choice() {
        return new ReferredDocumentType1Choice();
    }

    /**
     * Create an instance of {@link RemittanceAmount1 }
     * 
     * @return
     *     the new instance of {@link RemittanceAmount1 }
     */
    public RemittanceAmount1 createRemittanceAmount1() {
        return new RemittanceAmount1();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     * @return
     *     the new instance of {@link ActiveOrHistoricCurrencyAndAmount }
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link DocumentAdjustment1 }
     * 
     * @return
     *     the new instance of {@link DocumentAdjustment1 }
     */
    public DocumentAdjustment1 createDocumentAdjustment1() {
        return new DocumentAdjustment1();
    }

    /**
     * Create an instance of {@link GroupHeader37 }
     * 
     * @return
     *     the new instance of {@link GroupHeader37 }
     */
    public GroupHeader37 createGroupHeader37() {
        return new GroupHeader37();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation20 }
     * 
     * @return
     *     the new instance of {@link OriginalGroupInformation20 }
     */
    public OriginalGroupInformation20 createOriginalGroupInformation20() {
        return new OriginalGroupInformation20();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference13 }
     * 
     * @return
     *     the new instance of {@link OriginalTransactionReference13 }
     */
    public OriginalTransactionReference13 createOriginalTransactionReference13() {
        return new OriginalTransactionReference13();
    }

    /**
     * Create an instance of {@link PaymentTransactionInformation26 }
     * 
     * @return
     *     the new instance of {@link PaymentTransactionInformation26 }
     */
    public PaymentTransactionInformation26 createPaymentTransactionInformation26() {
        return new PaymentTransactionInformation26();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation22 }
     * 
     * @return
     *     the new instance of {@link PaymentTypeInformation22 }
     */
    public PaymentTypeInformation22 createPaymentTypeInformation22() {
        return new PaymentTypeInformation22();
    }

    /**
     * Create an instance of {@link StatusReason6Choice }
     * 
     * @return
     *     the new instance of {@link StatusReason6Choice }
     */
    public StatusReason6Choice createStatusReason6Choice() {
        return new StatusReason6Choice();
    }

    /**
     * Create an instance of {@link StatusReasonInformation8 }
     * 
     * @return
     *     the new instance of {@link StatusReasonInformation8 }
     */
    public StatusReasonInformation8 createStatusReasonInformation8() {
        return new StatusReasonInformation8();
    }

    /**
     * Create an instance of {@link NumberOfTransactionsPerStatus3 }
     * 
     * @return
     *     the new instance of {@link NumberOfTransactionsPerStatus3 }
     */
    public NumberOfTransactionsPerStatus3 createNumberOfTransactionsPerStatus3() {
        return new NumberOfTransactionsPerStatus3();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.03", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<>(_Document_QNAME, Document.class, null, value);
    }

}
