//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.25 at 11:54:17 AM EEST 
//


package montranMessage.iso.std.iso._20022.tech.xsd.pain_002_001;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.pain_002_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.pain_002_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerPaymentStatusReportV03EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public CustomerPaymentStatusReportV03EPC12116SCTINSTC2B2019V10 createCustomerPaymentStatusReportV03EPC12116SCTINSTC2B2019V10() {
        return new CustomerPaymentStatusReportV03EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link DocumentEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public DocumentEPC12116SCTINSTC2B2019V10 createDocumentEPC12116SCTINSTC2B2019V10() {
        return new DocumentEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification4EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification4EPC12116SCTINSTC2B2019V10 createBranchAndFinancialInstitutionIdentification4EPC12116SCTINSTC2B2019V10() {
        return new BranchAndFinancialInstitutionIdentification4EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PostalAddress6EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public PostalAddress6EPC12116SCTINSTC2B2019V10 createPostalAddress6EPC12116SCTINSTC2B2019V10() {
        return new PostalAddress6EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link AmountType3Choice }
     * 
     */
    public AmountType3Choice createAmountType3Choice() {
        return new AmountType3Choice();
    }

    /**
     * Create an instance of {@link AmountType3ChoiceEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public AmountType3ChoiceEPC12116SCTINSTC2B2019V10 createAmountType3ChoiceEPC12116SCTINSTC2B2019V10() {
        return new AmountType3ChoiceEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link Party6ChoiceEPC12116SCTINSTC2B2019V102 }
     * 
     */
    public Party6ChoiceEPC12116SCTINSTC2B2019V102 createParty6ChoiceEPC12116SCTINSTC2B2019V102() {
        return new Party6ChoiceEPC12116SCTINSTC2B2019V102();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification32EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public PartyIdentification32EPC12116SCTINSTC2B2019V10 createPartyIdentification32EPC12116SCTINSTC2B2019V10() {
        return new PartyIdentification32EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PaymentTransactionInformation25EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public PaymentTransactionInformation25EPC12116SCTINSTC2B2019V10 createPaymentTransactionInformation25EPC12116SCTINSTC2B2019V10() {
        return new PaymentTransactionInformation25EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7 }
     * 
     */
    public FinancialInstitutionIdentification7 createFinancialInstitutionIdentification7() {
        return new FinancialInstitutionIdentification7();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4EPC12116SCTINSTC2B2019V102 }
     * 
     */
    public OrganisationIdentification4EPC12116SCTINSTC2B2019V102 createOrganisationIdentification4EPC12116SCTINSTC2B2019V102() {
        return new OrganisationIdentification4EPC12116SCTINSTC2B2019V102();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference13 }
     * 
     */
    public OriginalTransactionReference13 createOriginalTransactionReference13() {
        return new OriginalTransactionReference13();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation22 }
     * 
     */
    public PaymentTypeInformation22 createPaymentTypeInformation22() {
        return new PaymentTypeInformation22();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation20 }
     * 
     */
    public OriginalGroupInformation20 createOriginalGroupInformation20() {
        return new OriginalGroupInformation20();
    }

    /**
     * Create an instance of {@link OriginalGroupInformation20EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public OriginalGroupInformation20EPC12116SCTINSTC2B2019V10 createOriginalGroupInformation20EPC12116SCTINSTC2B2019V10() {
        return new OriginalGroupInformation20EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification7EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public FinancialInstitutionIdentification7EPC12116SCTINSTC2B2019V10 createFinancialInstitutionIdentification7EPC12116SCTINSTC2B2019V10() {
        return new FinancialInstitutionIdentification7EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference13EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public OriginalTransactionReference13EPC12116SCTINSTC2B2019V10 createOriginalTransactionReference13EPC12116SCTINSTC2B2019V10() {
        return new OriginalTransactionReference13EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link RemittanceInformation5EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public RemittanceInformation5EPC12116SCTINSTC2B2019V10 createRemittanceInformation5EPC12116SCTINSTC2B2019V10() {
        return new RemittanceInformation5EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link CashAccount16EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public CashAccount16EPC12116SCTINSTC2B2019V10 createCashAccount16EPC12116SCTINSTC2B2019V10() {
        return new CashAccount16EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification4 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification4 createBranchAndFinancialInstitutionIdentification4() {
        return new BranchAndFinancialInstitutionIdentification4();
    }

    /**
     * Create an instance of {@link CashAccount16 }
     * 
     */
    public CashAccount16 createCashAccount16() {
        return new CashAccount16();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public CreditorReferenceInformation2EPC12116SCTINSTC2B2019V10 createCreditorReferenceInformation2EPC12116SCTINSTC2B2019V10() {
        return new CreditorReferenceInformation2EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link GroupHeader36EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public GroupHeader36EPC12116SCTINSTC2B2019V10 createGroupHeader36EPC12116SCTINSTC2B2019V10() {
        return new GroupHeader36EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link GroupHeader36 }
     * 
     */
    public GroupHeader36 createGroupHeader36() {
        return new GroupHeader36();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link OriginalPaymentInformation1 }
     * 
     */
    public OriginalPaymentInformation1 createOriginalPaymentInformation1() {
        return new OriginalPaymentInformation1();
    }

    /**
     * Create an instance of {@link StatusReason6ChoiceEPC12116SCTINSTC2B2019V102 }
     * 
     */
    public StatusReason6ChoiceEPC12116SCTINSTC2B2019V102 createStatusReason6ChoiceEPC12116SCTINSTC2B2019V102() {
        return new StatusReason6ChoiceEPC12116SCTINSTC2B2019V102();
    }

    /**
     * Create an instance of {@link StatusReasonInformation8EPC12116SCTINSTC2B2019V102 }
     * 
     */
    public StatusReasonInformation8EPC12116SCTINSTC2B2019V102 createStatusReasonInformation8EPC12116SCTINSTC2B2019V102() {
        return new StatusReasonInformation8EPC12116SCTINSTC2B2019V102();
    }

    /**
     * Create an instance of {@link StatusReasonInformation8EPC12116SCTINSTC2B2019V103 }
     * 
     */
    public StatusReasonInformation8EPC12116SCTINSTC2B2019V103 createStatusReasonInformation8EPC12116SCTINSTC2B2019V103() {
        return new StatusReasonInformation8EPC12116SCTINSTC2B2019V103();
    }

    /**
     * Create an instance of {@link StatusReasonInformation8 }
     * 
     */
    public StatusReasonInformation8 createStatusReasonInformation8() {
        return new StatusReasonInformation8();
    }

    /**
     * Create an instance of {@link OriginalPaymentInformation1EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public OriginalPaymentInformation1EPC12116SCTINSTC2B2019V10 createOriginalPaymentInformation1EPC12116SCTINSTC2B2019V10() {
        return new OriginalPaymentInformation1EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link StatusReason6Choice }
     * 
     */
    public StatusReason6Choice createStatusReason6Choice() {
        return new StatusReason6Choice();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link ServiceLevel8ChoiceEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public ServiceLevel8ChoiceEPC12116SCTINSTC2B2019V10 createServiceLevel8ChoiceEPC12116SCTINSTC2B2019V10() {
        return new ServiceLevel8ChoiceEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PartyIdentification32 }
     * 
     */
    public PartyIdentification32 createPartyIdentification32() {
        return new PartyIdentification32();
    }

    /**
     * Create an instance of {@link Party6ChoiceEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public Party6ChoiceEPC12116SCTINSTC2B2019V10 createParty6ChoiceEPC12116SCTINSTC2B2019V10() {
        return new Party6ChoiceEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PersonIdentification5EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public PersonIdentification5EPC12116SCTINSTC2B2019V10 createPersonIdentification5EPC12116SCTINSTC2B2019V10() {
        return new PersonIdentification5EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmountEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmountEPC12116SCTINSTC2B2019V10 createActiveOrHistoricCurrencyAndAmountEPC12116SCTINSTC2B2019V10() {
        return new ActiveOrHistoricCurrencyAndAmountEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public StructuredRemittanceInformation7EPC12116SCTINSTC2B2019V10 createStructuredRemittanceInformation7EPC12116SCTINSTC2B2019V10() {
        return new StructuredRemittanceInformation7EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link PartyIdentification32EPC12116SCTINSTC2B2019V102 }
     * 
     */
    public PartyIdentification32EPC12116SCTINSTC2B2019V102 createPartyIdentification32EPC12116SCTINSTC2B2019V102() {
        return new PartyIdentification32EPC12116SCTINSTC2B2019V102();
    }

    /**
     * Create an instance of {@link PaymentTransactionInformation25 }
     * 
     */
    public PaymentTransactionInformation25 createPaymentTransactionInformation25() {
        return new PaymentTransactionInformation25();
    }

    /**
     * Create an instance of {@link PartyIdentification32EPC12116SCTINSTC2B2019V103 }
     * 
     */
    public PartyIdentification32EPC12116SCTINSTC2B2019V103 createPartyIdentification32EPC12116SCTINSTC2B2019V103() {
        return new PartyIdentification32EPC12116SCTINSTC2B2019V103();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public OrganisationIdentification4EPC12116SCTINSTC2B2019V10 createOrganisationIdentification4EPC12116SCTINSTC2B2019V10() {
        return new OrganisationIdentification4EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link StatusReasonInformation8EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public StatusReasonInformation8EPC12116SCTINSTC2B2019V10 createStatusReasonInformation8EPC12116SCTINSTC2B2019V10() {
        return new StatusReasonInformation8EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link CustomerPaymentStatusReportV03 }
     * 
     */
    public CustomerPaymentStatusReportV03 createCustomerPaymentStatusReportV03() {
        return new CustomerPaymentStatusReportV03();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation22EPC12116SCTINSTC2B2019V10 }
     * 
     */
    public PaymentTypeInformation22EPC12116SCTINSTC2B2019V10 createPaymentTypeInformation22EPC12116SCTINSTC2B2019V10() {
        return new PaymentTypeInformation22EPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link StatusReason6ChoiceEPC12116SCTINSTC2B2019V10 }
     * 
     */
    public StatusReason6ChoiceEPC12116SCTINSTC2B2019V10 createStatusReason6ChoiceEPC12116SCTINSTC2B2019V10() {
        return new StatusReason6ChoiceEPC12116SCTINSTC2B2019V10();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentEPC12116SCTINSTC2B2019V10 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", name = "Document")
    public JAXBElement<DocumentEPC12116SCTINSTC2B2019V10> createDocument(DocumentEPC12116SCTINSTC2B2019V10 value) {
        return new JAXBElement<DocumentEPC12116SCTINSTC2B2019V10>(_Document_QNAME, DocumentEPC12116SCTINSTC2B2019V10 .class, null, value);
    }

}
